受け入れ停止ページを受け入れ再開に修正,news欄追記
TUS-OSK/oskt.us pull request #96
Opened 2020-10-31 08:50 UTC by pppp-q

・トップページ右上にリンクがございました"入部受付停止"ページの内容を"受付再開"に改変
・news欄に上記更新の旨を記載

2020-11-02 06:12 UTC, JF1HNL requested changes
文面の変更をお願いします。

2020-11-02 06:12 UTC, JF1HNL commented on page/2020/correspondence-covid-19.md
> +入部をご希望の際は弊サークルの [Twitter] (https://twitter.com/tus_osk) までDMいただけますようお願いいたします。
```suggestion
入部をご希望の際は [こちら](#contact) までご連絡いただけますようお願いいたします。   
```

2020-11-08 04:07 UTC, momoogles commented
バージョンが新しくなったのでこのブランチ自分がコンフリ解消しておきます！

2020-11-08 06:04 UTC, JF1HNL reviewed
日時したsuggestionつけておきました。

2020-11-08 06:04 UTC, JF1HNL commented on page/2020/correspondence-covid-19.md
> +<span style="color: red; ">2020/11/** 追記</span>
```suggestion
<span style="color: red; ">2020/11/09 追記</span>  
```

2020-11-08 06:04 UTC, JF1HNL commented on page/main/news.md
> +**2020/11/**** [2020 年度新入生受け入れ再開につきまして](#page/2020/correspondence-covid-19)
```suggestion
**2020/11/09** [2020 年度新入生受け入れ再開につきまして](#page/2020/correspondence-covid-19)
```

2020-11-08 06:08 UTC, JF1HNL commented
コンフリクト解消したら、Approve付けます。

2020-11-08 07:42 UTC, momoogles approved these changes

2020-11-08 07:42 UTC, momoogles commented on page/main/news.md
>  **2020/06/28** [2020 年度新入生受け入れにつきまして](#page/2020/correspondence-covid-19)
こっちを消さないと受け入れ再開の文章が表示されちゃいますね

2020-11-08 07:42 UTC, momoogles commented on page/main/news.md
>  **2020/06/28** [2020 年度新入生受け入れにつきまして](#page/2020/correspondence-covid-19)
今回修正した記事を新しい記事として追加する形にしますね

バルーンも修正するようにします

2020-11-08 08:15 UTC, momoogles commented
修正しました！申し訳ないのですが再レビューをお願いします！

2020-11-08 08:22 UTC, JF1HNL commented on _articles/markdowns/2020/correspondence-covid-19.md
> +> ! [2020年度新入生の受け入れは再開されました](/articles/2020/correspondence-covid-19-2)
```suggestion
> [2020年度新入生の受け入れは再開されました](/articles/2020/correspondence-covid-19-2)
```
`!`って何か意味があったりしますか、、、？

2020-11-08 08:22 UTC, JF1HNL commented on _articles/markdowns/2020/correspondence-covid-19.md
> +> ! [2020年度新入生の受け入れは再開されました](/articles/2020/correspondence-covid-19-2)
@momoogles

2020-11-08 08:27 UTC, JF1HNL commented
![スクリーンショット 2020-11-08 17 25 45](https://user-images.githubusercontent.com/38598126/98460429-b0110700-21e7-11eb-9875-8cc8685863d6.png)

文字数調整をしたい。

2020-11-08 08:28 UTC, momoogles commented on _articles/markdowns/2020/correspondence-covid-19.md
> +> ! [2020年度新入生の受け入れは再開されました](/articles/2020/correspondence-covid-19-2)
注意！みたいな意味で適当に追加したので、消しちゃって大丈夫です！

2020-11-08 08:29 UTC, pppp-q commented
入部・見学をご希望の方へ
とか、、？(まだ長い)

2020-11-08 08:37 UTC, momoogles commented
(変更お任せします！残りの修正よろしくお願いいたします！)

2020-11-08 09:02 UTC, JF1HNL commented
> 入部・見学をご希望の方へ
> とか、、？(まだ長い)

👏 
![スクリーンショット 2020-11-08 17 57 46](https://user-images.githubusercontent.com/38598126/98461055-7db5d880-21ec-11eb-9732-73dc5f13af75.png)

2020-11-08 12:10 UTC, JF1HNL approved these changes

2020-11-08 12:10 UTC, merged